<?php

namespace App\Http\Requests\administrator;

//use Illuminate\Foundation\Http\FormRequest;
use App\Http\Requests\FormRequest;
class MenuRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        switch ($this->methods){
            case 'createmenu';
                return [
                    'parent_id'=>'nullable|integer',
                    'title'=>'required|string|min:2|max:10',
                    'uri'=>'required|string|min:2|max:50',
                ];
            case 'del';
                return [
                    'id'=>'required|integer',
                ];
        }

    }

    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'parent_id.integer'=>'上级ID必须是整数',
            'title.required'=>'菜单名称不能为空',
            'title.string'=>'菜单名称必须是字符串',
            'title.min'=>'菜单名称最小为2个字符',
            'title.max'=>'菜单名称最大为50个字符',
            'uri.required'=>'路径不能为空',
            'uri.string'=>'路径必须是字符串',
            'uri.min'=>'路径最小为2个字符',
            'uri.max'=>'路径最大为50个字符',
            'id.required'=>'ID不能为空',
            'id.integer'=>'ID必须是整数',

        ];
    }
}
