<?php

namespace App\Http\Requests\administrator;

use App\Http\Requests\FormRequest;
class permissionRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        switch ($this->methods){
            case 'create';
                return [
                    'name'=>'required|string|max:15|unique:permissions',
                    'http_path'=>'required|string|max:50|unique:permissions',
                    'http_method'=>'required|string|max:10',
                ];
            case 'del';
                return [
                    'id'=>'required|integer',
                ];
        }

    }


    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'name.required'=>'权限名称不能为空',
            'name.string'=>'权限名称必须是字符串',
            'name.max'=>'权限名称最大为15个字符',
            'name.unique'=>'已有此权限名称，请更换名称',
            'http_path.required'=>'权限路径不能为空',
            'http_path.string'=>'权限路径必须是字符串',
            'http_path.unique'=>'已有此权限路径，请更换路径',
            'http_path.max'=>'权限路径最大为50个字符',
            'http_method.required'=>'路径方法不能为空',
            'http_method.string'=>'路径方法必须是字符串',
            'http_method.max'=>'路径方法最大为10个字符',
            'id.required'=>'ID不能为空',
            'id.integer'=>'ID必须是整数',
        ];
    }
}
