<?php

namespace App\Http\Requests\administrator;

use App\Http\Requests\FormRequest;
class RoleRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        switch ($this->methods){
            case 'createrole';
                return [
                    'name' =>'required|string|max:15|unique:roles',
                ];
            case 'del';
                return [
                    'id'=>'required|integer',
                ];
            case 'rolemenudel';
                return [
                    'role_id'=>'required|integer',
                    'menu_id'=>'required|array|max:50'
                ];
            case 'rolemenuadd';
                return [
                    'role_id'=>'required|integer',
                    'menu_id'=>'required|array|max:50'
                ];
            case 'rolePermissionCreate';
                return [
                    'role_id'=>'required|integer',
                    'permission_id'=>'required|array|max:50'
                ];
            case 'rolePermissionDel';
                return [
                    'role_id'=>'required|integer',
                    'permission_id'=>'required|array|max:50'
                ];
        }
        

    }
    
    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'name.required'=>'角色名称不能为空',
            'name.string'=>'角色名称必须是字符串',
            'name.max'=>'角色名称最大为15个字符',
            'name.unique'=>'已有此角色名称，请更换名称',
            'id.required'=>'ID不能为空',
            'id.integer'=>'ID必须是整数',
            'role_id.required'=>'角色ID不能为空',
            'role_id.integer'=>'角色ID必须是整数',
            'menu_id.required'=>'菜单ID不能为空',
            'menu_id.array'=>'菜单ID必须是数组',
            'menu_id.max'=>'菜单ID最大为50字符',
            'permission_id.required'=>'菜单ID不能为空',
            'permission_id.array'=>'菜单ID必须是数组',
            'permission_id.max'=>'菜单ID最大为50字符',

        ];
    }
}
