<?php

namespace App\Http\Requests\administrator;

//use Illuminate\Foundation\Http\FormRequest;
use App\Http\Requests\FormRequest;

class UserRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
//        dd($this->methods);
        switch ($this->methods){
            case 'create';
                    return [
                        'name' =>'required|max:10|unique:users',
                        'email' => 'required|email|max:50|unique:users',
                        'password' => 'required|min:6|max:30|confirmed',
                    ];
            case 'register';
                return [
                    'name' =>'required|max:10|unique:users',
                    'email' => 'required|email|max:50|unique:users',
                    'password' => 'required|min:6|max:30|confirmed',
                ];
            case 'del';
                    return [
                        'id'=>'required|integer',
                    ];
            case 'userandrole';
                    return [
                        'id'=>'required|integer',
                        'roleIds'=>'required|array',
                    ];
            case 'userRoleDel';
                    return [
                        'id'=>'required|integer',
                        'roleIds'=>'required|array|max:50',
                    ];


        }


    }

    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'name.required'=>'名称不能为空',
            'name.max'=>'名称最大为10个字符',
            'name.unique'=>'此名称已存在，请更换名称',
            'email.required'=>'邮箱不能为空',
            'email.max'=>'邮箱最大为50个字符',
            'email.email'=>'邮箱格式不正确，请检查后再提交',
            'email.unique'=>'此邮箱已存在，请更换邮箱',
            'password.required'=>'密码不能为空',
            'password.max'=>'密码最大为30个字符',
            'password.min'=>'密码最小为6个字符',
            'password.confirmed'=>'两次密码不一致密码',
            'id.required'=>'ID不能为空',
            'id.integer'=>'ID不能为空',
            'roleIds.required'=>'角色ID不能为空',
            'roleIds.array'=>'角色ID必须是数组格式',
            'roleIds.max'=>'角色ID最大为50字符',
        ];
    }
}
