<?php

namespace App\Http\Requests\administrator;

//use Illuminate\Foundation\Http\FormRequest;
use App\Http\Requests\FormRequest;

class UserRequests extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' =>'required|string|max:2',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
        ];
    }

    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'name.required'=>'M名称不能为空',
            'email.required'=>'邮箱不能为空',
            'password.required'=>'密码不能为空',
        ];
    }
}
